### PR TITLE
Ability to specify options for modules

### PR DESCRIPTION
**Pull request by ArtemMolotov**
Example:
 
```js
b.plugin('tinyify', {
  // ...
  modulesOptions: {
    uglify: {output: {ascii_only: false}},
  }
})
```

Please test the library after me again if you plan to accept the RP. Thank you!)

### CODE REVIEW

**Comment by ArtemMolotov** [comment]
I apologize for the publication of PR with errors. 
Seems fixed.

**Comment by goto-bus-stop** [comment]
I think, if options are necessary, the best way to do it is to apply the plugins manually, as mentioned at the end of the readme here: https://github.com/browserify/tinyify#more-options

Is there a specific option you need? if the current set of defaults breaks something, we could change the default

**Comment by ArtemMolotov** [comment]
`ascii_only` increases the size of the bundle, that's why I wanted to disable it.
This is hardly a significant reason to change the default value. But thank you...
I'll create a fork :)

**Comment by toddself** [comment]
IIRC ascii_only fixes a bug with safari which why its enabled

**Pull request closed without merging**
